name: aws_lambda_runtime
version: 1.1.1
description: |-
  A powerful runtime to build Lambda functions in Dart with native AWS events.
homepage: https://github.com/amondnet/aws-lambda-dart-runtime
#documentation: https://awslabs.github.io/aws-lambda-dart-runtime/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.0.1
  meta: ^1.3.0
  http: ^0.13.1

dev_dependencies:
  json_serializable: ^4.1.0
  build_runner: ^1.7.2
  test: ^1.16.8
  mockito: ^5.0.3
  pedantic: ^1.11.0
  lints: ^1.0.1